apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthz
  namespace: cloudradar
  labels:
    app.kubernetes.io/name: healthz
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /healthz
            pathType: Prefix
            backend:
              service:
                name: healthz
                port:
                  number: 80
