apiVersion: v1
kind: Service
metadata:
  name: processor
  namespace: cloudradar
  labels:
    app.kubernetes.io/name: processor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: processor
  ports:
    - name: http
      port: 80
      targetPort: http
