apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - servicemonitor-processor.yaml
  - servicemonitor-ingester.yaml
  - servicemonitor-redis-exporter.yaml
  - servicemonitor-traefik.yaml
