apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudradar-processor
  labels:
    app.kubernetes.io/part-of: cloudradar
spec:
  namespaceSelector:
    matchNames:
      - cloudradar
  selector:
    matchLabels:
      app.kubernetes.io/name: processor
  endpoints:
    - port: http
      path: /metrics/prometheus
      interval: 30s
