apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: data
  labels:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/part-of: cloudradar
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/part-of: cloudradar
  ports:
    - name: metrics
      port: 9121
      targetPort: metrics
