apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data

resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml
  - exporter-deployment.yaml
  - exporter-service.yaml
