apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-scale-ingester
  namespace: cloudradar
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    resourceNames: ["ingester"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-scale-ingester
  namespace: cloudradar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-scale-ingester
subjects:
  - kind: ServiceAccount
    name: admin-scale
    namespace: cloudradar
