apiVersion: v1
kind: Service
metadata:
  name: admin-scale
  namespace: cloudradar
  labels:
    app.kubernetes.io/name: admin-scale
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: admin-scale
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 32737
