apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secretstore.yaml
  - grafana-domain.yaml
  - grafana-secret.yaml
  - opensky-secret.yaml
  - processor-aircraft-db.yaml
