apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opensky-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-parameter-store
  target:
    name: opensky-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        api-key: "{{ .apiKey }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: /cloudradar/opensky-api-key
