apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs-csi-driver
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    chart: aws-ebs-csi-driver
    targetRevision: "2.34.0"
    helm:
      values: |
        controller:
          replicaCount: 1
        node:
          tolerateAllTaints: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
