apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ebs-csi-application.yaml
  - admin-scale
  - frontend
  - health
  - dashboard
  - ingester
  - processor
  - redis
  - monitoring
  - storageclass-gp3.yaml
