apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ebs-csi-application.yaml
  - admin-scale
  - health
  - ingester
  - redis
  - storageclass-gp3.yaml
